version: '3.9'

services:
  nextserver:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SECRET=<SECRET_PHRASE><SECRET_PHRASE><SECRET_PHRASE>
      - TZ=America/Caracas
      - NODE_ENV=production
      # ID of status: answered
      - ANSWERED_STATUS=1
      # ID of status: reviewed
      - REVISED_STATUS=5
      # ID of status: updated (for the user)
      - UPDATED_STATUS=6
    volumes:
      - sqlite:/user/app/db
    ports:
      - '3000:3000'
    restart: no

volumes:
  sqlite:
