version: '3.9'

services:
  nextserver:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ANSWERED_STATUS: ${ANSWERED_STATUS}
        CREATED_STATUS: ${CREATED_STATUS}
        DATABASE_URL: ${DATABASE_URL}
        HOSTNAME: ${HOSTNAME}
        REVISED_STATUS: ${REVISED_STATUS}
        SECRET: ${SECRET}
        UPDATED_STATUS: ${UPDATED_STATUS}
    volumes:
      - sqlite:/app/db
    ports:
      - '3000:3000'
    restart: no

volumes:
  sqlite:
    
