version: '3.9'

services:
  user-form:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL="file:./dev.db" 
      - SECRET=<SECRET_PHRASE><SECRET_PHRASE><SECRET_PHRASE>
      - TZ=America/Caracas
      - NODE_ENV=production
      
    ports:
      - '3000:3000'
    restart: always
