import './globals.css'

export const metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='bg-gray-800'>{children}</body>
    </html>
  )
}
