import '../globals.css'

export const metadata = {
  title: 'Login',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <html lang="en" >
        <body className="min-w-screen min-h-screen bg-gray-800 flex flex-col items-center justify-center p-5">
          {children}
        </body>
      </html>
  );
}
